### ISSUE TITLE
Questions about learning rate

### ISSUE THREAD

**Issue by AssassinJay** [cfzd/Ultra-Fast-Lane-Detection-v2#72]
Thanks for the great work, I have some questions about the learning rate. 

In the paper, the learning rate is set to 0.1, the batch size is set to 16 per GPU(3090), and the epoch is set to 30, but I didn't find in the paper how much GPU is used. 

My device is a single 3090, what config should I set?

I tried batch size 16, epoch 50, and lr 0.05 for the Culane dataset, and I got pretty much the same result as in the paper.

**Comment by cfzd** [comment]
@AssassinJay 
The number of GPU in CULane and Curvelanes is 8. The number of GPU in Tusimple is 1.

Theoretically, you can set the lr to 0.1/8. But it seems 0.05 is also OK.

**Comment by cfzd** [comment]
@AssassinJay 
I think you can use the settings from the code instead of paper, since the models are produced exactly by the code config. 

The default config of culane is: 8 GPU, 32 batch size, 0.05 lr. If you want to decrease the batch size to 16, I think you can also decrease the lr to 0.025. But these config is based on 8 GPU. If you use single GPU, you might need to further decrease the lr to 0.025/8.

The above derivation strictly follows the "Linear scaling rule". But it is not always true. You can use it as a guide, but the ultimate setting can only from your experiments.

**Comment by AssassinJay** [comment]
@cfzd 
Thank you again, I think I have got the trick!
